# Generated by Django 5.0.1 on 2024-01-16 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.company')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.province')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.city')),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_origin', models.CharField(max_length=50)),
                ('address_destination', models.CharField(max_length=50)),
                ('feedback', models.TextField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.company')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_origin', models.CharField(max_length=20)),
                ('city_destination', models.CharField(max_length=20)),
                ('datetime_departure', models.DateTimeField()),
                ('real_datetime_arrival', models.DateTimeField(default=None, null=True)),
                ('estimated_datetime_arrival', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('fee', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.company')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.driver')),
                ('plate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.vehicle')),
            ],
        ),
    ]
