# Generated by Django 5.0.3 on 2024-04-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='surname',
            new_name='last_name',
        ),
    ]
