# Generated by Django 5.0.3 on 2024-08-09 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='nationality',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.nationality'),
        ),
    ]
