# Generated by Django 5.0.3 on 2024-09-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='paid_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
