# Generated by Django 5.0.3 on 2024-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='address_destination_number',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='address_origin_number',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
