# Generated by Django 5.0.3 on 2024-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='ocuppied_seats',
            field=models.IntegerField(default=0),
        ),
    ]
