# Generated by Django 5.1.1 on 2024-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='url',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
