# Generated by Django 5.0.3 on 2024-04-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0002_travel_ocuppied_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='ocuppied_seats',
            new_name='seats_left',
        ),
    ]
