# Generated by Django 5.0.3 on 2024-08-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0002_traveler_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.nationality'),
        ),
    ]
