# Generated by Django 5.0.3 on 2024-04-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0002_rename_name_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='abbreviation',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
