# Generated by Django 5.0.3 on 2024-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0002_traveler_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='addr_origin',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='addr_origin_num',
        ),
        migrations.AddField(
            model_name='travel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='geolocation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
