# Generated by Django 5.1.1 on 2024-09-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0002_waypoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='cbu',
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
    ]
