# Generated by Django 5.0.3 on 2024-08-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0003_alter_traveler_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='dni_description',
            field=models.CharField(default=None, max_length=9, null=True),
        ),
    ]
