# Generated by Django 5.0.3 on 2024-09-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0003_remove_travel_addr_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='addr_dest',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='addr_dest_num',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='addr_ori',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='addr_ori_num',
        ),
        migrations.AddField(
            model_name='traveler',
            name='address_destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='address_origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
