# Generated by Django 5.0.3 on 2024-07-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0003_rename_address_destination_traveler_addr_dest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='addr_origin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='addr_origin_num',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traveler',
            name='addr_dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='addr_dest_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='addr_ori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='addr_ori_num',
            field=models.CharField(max_length=10),
        ),
    ]
