# Generated by Django 5.0.3 on 2024-04-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0003_province_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='abbreviation',
            field=models.CharField(max_length=4),
        ),
    ]
