# Generated by Django 5.0.3 on 2024-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0003_rename_ocuppied_seats_travel_seats_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='dni',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='phone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
