# Generated by Django 5.0.3 on 2024-04-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0004_traveler_dni_traveler_email_traveler_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='client',
        ),
    ]
