# Generated by Django 5.1.1 on 2024-10-03 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0004_alter_company_options_alter_travel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveler',
            options={'verbose_name': 'Pasajero pendiente de devolución', 'verbose_name_plural': 'Pasajeros pendientes de devolución'},
        ),
        migrations.RemoveField(
            model_name='travel',
            name='cbu',
        ),
        migrations.AddField(
            model_name='company',
            name='cbu',
            field=models.CharField(default='0', max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.driver', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En Proceso', 'En Proceso'), ('Agendado', 'Agendado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Pagado', 'Pagado')], default='Borrador', max_length=50, verbose_name='Estado del viaje'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.vehicle', verbose_name='Vehiculo'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='paid_amount',
            field=models.IntegerField(verbose_name='Total pagado'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='payment_status',
            field=models.CharField(default='En Proceso', max_length=50, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
    ]
