# Generated by Django 5.0.3 on 2024-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0004_alter_province_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
