# Generated by Django 5.0.3 on 2024-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0004_travel_addr_origin_travel_addr_origin_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='url',
            field=models.CharField(default='url', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traveler',
            name='feedback',
            field=models.TextField(default='-', max_length=200, null=True),
        ),
    ]
