# Generated by Django 5.0.3 on 2024-08-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0005_alter_driver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='city_destination',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='city_origin',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='datetime_departure',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='estimated_datetime_arrival',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='seats_left',
        ),
        migrations.AlterField(
            model_name='travel',
            name='period',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.period'),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('fee', models.IntegerField(default=0, null=True)),
                ('seats_occupied', models.IntegerField(default=0)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.travel')),
            ],
        ),
        migrations.AlterField(
            model_name='traveler',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineris.segment'),
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_datetime_arrival', models.DateTimeField()),
                ('node_number', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.city')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.travel')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='waypoint_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='waypoint_destination', to='itineris.waypoint'),
        ),
        migrations.AddField(
            model_name='segment',
            name='waypoint_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='waypoint_origin', to='itineris.waypoint'),
        ),
    ]
