# Generated by Django 5.0.3 on 2024-04-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0005_alter_travel_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='abbreviation',
            new_name='acronym',
        ),
    ]
