# Generated by Django 5.0.3 on 2024-09-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0005_traveler_geocode_destination_traveler_geocode_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='geolocation',
            new_name='geocode',
        ),
    ]
