# Generated by Django 5.0.3 on 2024-07-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0005_travel_url_alter_traveler_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('weekday', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='period',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itineris.period'),
        ),
    ]
