# Generated by Django 5.0.3 on 2024-04-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0006_rename_abbreviation_province_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.CharField(default='Confirmado', max_length=50),
        ),
        migrations.AddField(
            model_name='traveler',
            name='status',
            field=models.CharField(default='En Proceso', max_length=50),
        ),
    ]
