# Generated by Django 5.0.3 on 2024-07-31 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0006_period_travel_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('weekday_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='period',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='itineris.weekday'),
        ),
    ]
