# Generated by Django 5.0.3 on 2024-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0007_weekday_alter_period_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='description',
        ),
        migrations.RemoveField(
            model_name='period',
            name='weekday',
        ),
        migrations.AddField(
            model_name='period',
            name='weekday',
            field=models.ManyToManyField(to='itineris.weekday'),
        ),
    ]
