# Generated by Django 5.0.3 on 2024-04-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0007_travel_status_traveler_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='car_model',
        ),
    ]
