# Generated by Django 5.0.3 on 2024-08-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0007_alter_waypoint_node_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='travel',
            new_name='segment',
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(default='Borrador', max_length=50),
        ),
    ]
