# Generated by Django 5.0.3 on 2024-08-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0008_remove_period_description_remove_period_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='weekday',
        ),
        migrations.AddField(
            model_name='period',
            name='weekdays',
            field=models.ManyToManyField(related_name='weekdays', to='itineris.weekday'),
        ),
    ]
