# Generated by Django 5.0.3 on 2024-08-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0009_remove_period_weekday_period_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='travel',
            name='url',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
