# Generated by Django 5.0.3 on 2024-05-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0009_alter_travel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
