# Generated by Django 5.0.3 on 2024-08-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0010_alter_period_end_date_alter_travel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='url',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
