# Generated by Django 5.0.3 on 2024-05-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0010_driver_active_vehicle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='payment_status',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
