# Generated by Django 5.0.3 on 2024-08-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0011_alter_travel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
