# Generated by Django 5.0.3 on 2024-08-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineris', '0012_alter_period_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='status',
            new_name='payment_status',
        ),
    ]
